#define FASTHAL_DECLAREPORT(CODE)\
FASTHAL_DECLAREREGISTER(port ## CODE, PORT ## CODE)\
FASTHAL_DECLAREREGISTER(pin ## CODE, PIN ## CODE)\
FASTHAL_DECLAREREGISTER(ddr ## CODE, DDR ## CODE)

#ifdef PORTA
FASTHAL_DECLAREPORT(A)
#endif
#ifdef PORTB
FASTHAL_DECLAREPORT(B)
#endif
#ifdef PORTC
FASTHAL_DECLAREPORT(C)
#endif
#ifdef PORTD
FASTHAL_DECLAREPORT(D)
#endif
#ifdef PORTE
FASTHAL_DECLAREPORT(E)
#endif
#ifdef PORTF
FASTHAL_DECLAREPORT(F)
#endif
#ifdef PORTG
FASTHAL_DECLAREPORT(G)
#endif
#ifdef PORTH
FASTHAL_DECLAREPORT(H)
#endif
#ifdef PORTJ
FASTHAL_DECLAREPORT(J)
#endif
#ifdef PORTK
FASTHAL_DECLAREPORT(K)
#endif
#ifdef PORTL
FASTHAL_DECLAREPORT(L)
#endif

#undef FASTHAL_DECLAREPORT