#define FH_DECLARE_PORT(CODE)\
FH_DECLARE_REGISTER(port ## CODE, PORT ## CODE)\
FH_DECLARE_REGISTER(pin ## CODE, PIN ## CODE)\
FH_DECLARE_REGISTER(ddr ## CODE, DDR ## CODE)

#ifdef PORTA
FH_DECLARE_PORT(A)
#endif
#ifdef PORTB
FH_DECLARE_PORT(B)
#endif
#ifdef PORTC
FH_DECLARE_PORT(C)
#endif
#ifdef PORTD
FH_DECLARE_PORT(D)
#endif
#ifdef PORTE
FH_DECLARE_PORT(E)
#endif
#ifdef PORTF
FH_DECLARE_PORT(F)
#endif
#ifdef PORTG
FH_DECLARE_PORT(G)
#endif
#ifdef PORTH
FH_DECLARE_PORT(H)
#endif
#ifdef PORTJ
FH_DECLARE_PORT(J)
#endif
#ifdef PORTK
FH_DECLARE_PORT(K)
#endif
#ifdef PORTL
FH_DECLARE_PORT(L)
#endif

#undef FH_DECLARE_PORT