#define FH_DECLAREUART_REGISTERS(NAME, CODE)\
    FASTHAL_DECLAREREGISTER_ONLY(ubrr ## NAME, UBRR ## CODE)\
	FASTHAL_DECLAREREGISTER_ONLY(ubrr ## NAME ## h, UBRR ## CODE ## H)\
	FASTHAL_DECLAREREGISTER_ONLY(ubrr ## NAME ## l, UBRR ## CODE ## L)\
	FASTHAL_DECLAREREGISTER_ONLY(ucsr ## NAME ## a, UCSR ## CODE ## A)\
	FASTHAL_DECLAREREGISTER_ONLY(ucsr ## NAME ## b, UCSR ## CODE ## B)\
	FASTHAL_DECLAREREGISTER_ONLY(ucsr ## NAME ## c, UCSR ## CODE ## C)\
	FASTHAL_DECLAREREGISTER_ONLY(udr ## NAME, UDR ## CODE)\

#ifdef UBBR
FH_DECLAREUART_REGISTERS(0,);
#define FH_HAS_UART0
#endif
#ifdef UBBR0
FH_DECLAREUART_REGISTERS(0,0);
#define FH_HAS_UART0
#endif
#ifdef UBBR1
FH_DECLAREUART_REGISTERS(1,1);
#define FH_HAS_UART1
#endif
#ifdef UBBR2
FH_DECLAREUART_REGISTERS(2,2);
#define FH_HAS_UART2
#endif
#ifdef UBBR3
FH_DECLAREUART_REGISTERS(3,3);
#define FH_HAS_UART3
#endif