// ********************* Generated by a tool *********************
/*
  pins_fastduino.hpp - Pin definition functions for Arduino
  Part of Arduino - http://www.arduino.cc/

  Copyright (c) 2007 David A. Mellis

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General
  Public License along with this library; if not, write to the
  Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA  02111-1307  USA
*/

#ifndef FH_PINS_FASTDUINO_H_
#define FH_PINS_FASTDUINO_H_



#if defined(__AVR_ATmega328PB__)
# define NUM_DIGITAL_PINS           24
# define NUM_ANALOG_INPUTS          8
# define analogInputToDigitalPin(p) ((p < 8) ? (p) + 14 : -1)
#else
# define NUM_DIGITAL_PINS           20
# define NUM_ANALOG_INPUTS          8
# define analogInputToDigitalPin(p) ((p < 6) ? (p) + 14 : -1)
#endif

#if defined(__AVR_ATmega328PB__)
# define digitalPinHasPWM(p)        ((p) == 0 || (p) == 1 || (p) == 2 || (p) == 3 || (p) == 5 || (p) == 6 || (p) == 9 || (p) == 10 || (p) == 11)
#elif defined(__AVR_ATmega8__)
# define digitalPinHasPWM(p)        ((p) == 9 || (p) == 10 || (p) == 11)
#else
# define digitalPinHasPWM(p)        ((p) == 3 || (p) == 5 || (p) == 6 || (p) == 9 || (p) == 10 || (p) == 11)
#endif

#define PIN_SPI_SS     (10)
#define PIN_SPI_MOSI   (11)
#define PIN_SPI_MISO   (12)
#define PIN_SPI_SCK    (13)

static constexpr std::uint8_t SS   = PIN_SPI_SS;
static constexpr std::uint8_t MOSI = PIN_SPI_MOSI;
static constexpr std::uint8_t MISO = PIN_SPI_MISO;
static constexpr std::uint8_t SCK  = PIN_SPI_SCK;

#define PIN_WIRE_SDA   (18)
#define PIN_WIRE_SCL   (19)

static constexpr std::uint8_t SDA = PIN_WIRE_SDA;
static constexpr std::uint8_t SCL = PIN_WIRE_SCL;

#if defined(__AVR_ATmega328PB__)
#define PIN_SPI1_SS    (20)
#define PIN_SPI1_MOSI  (21)
#define PIN_SPI1_MISO  (14)
#define PIN_SPI1_SCK   (15)

static constexpr std::uint8_t SS1   = PIN_SPI1_SS;
static constexpr std::uint8_t MOSI1 = PIN_SPI1_MOSI;
static constexpr std::uint8_t MISO1 = PIN_SPI1_MISO;
static constexpr std::uint8_t SCK1  = PIN_SPI1_SCK;

#define PIN_WIRE1_SDA   (22)
#define PIN_WIRE1_SCL   (23)

static constexpr std::uint8_t SDA1 = PIN_WIRE1_SDA;
static constexpr std::uint8_t SCL1 = PIN_WIRE1_SCL;
#endif

#define LED_BUILTIN 13

#define PIN_A0   (14)
#define PIN_A1   (15)
#define PIN_A2   (16)
#define PIN_A3   (17)
#define PIN_A4   (18)
#define PIN_A5   (19)
#define PIN_A6   (20)
#define PIN_A7   (21)

static constexpr std::uint8_t A0 = PIN_A0;
static constexpr std::uint8_t A1 = PIN_A1;
static constexpr std::uint8_t A2 = PIN_A2;
static constexpr std::uint8_t A3 = PIN_A3;
static constexpr std::uint8_t A4 = PIN_A4;
static constexpr std::uint8_t A5 = PIN_A5;
static constexpr std::uint8_t A6 = PIN_A6;
static constexpr std::uint8_t A7 = PIN_A7;

#define digitalPinToPCICR(p)    (((p) >= 0 && (p) <= 23) ? (&PCICR) : ((std::uint8_t *)0))
#define digitalPinToPCICRbit(p) (((p) <= 7) ? 2 : (((p) <= 13) ? 0 : 1))
#define digitalPinToPCMSK(p)    (((p) <= 7) ? (&PCMSK2) : (((p) <= 13) ? (&PCMSK0) : (((p) <= 23) ? (&PCMSK1) : ((std::uint8_t *)0))))
#define digitalPinToPCMSKbit(p) (((p) <= 7) ? (p) : (((p) <= 13) ? ((p) - 8) : ((p) - 14)))

#define digitalPinToInterrupt(p)  ((p) == 2 ? 0 : ((p) == 3 ? 1 : NOT_AN_INTERRUPT))

#if (2 + 2 == 4)

// these arrays map port names (e.g. port B) to the
// appropriate addresses for various functions (e.g. reading
// and writing)






constexpr std::uint8_t ino_port_num[] = {
	4, /* 0 */
	4,
	4,
	4,
	4,
	4,
	4,
	4,
	2, /* 8 */
	2,
	2,
	2,
	2,
	2,
	3, /* 14 */
	3,
	3,
	3,
	3,
	3,
#if defined(__AVR_ATmega3282__)
	5, /* 20 */
	5,
	5,
	5,
#endif
};

constexpr std::uint8_t ino_pin_num[] = {
	0, /* 0, port D */
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	0, /* 8, port B */
	1,
	2,
	3,
	4,
	5,
	0, /* 14, port C */
	1,
	2,
	3,
	4,
	5,
#if defined(__AVR_ATmega328PB__
	2, /* 20, port E */
	3,
	0,
	1,
#endif
};

constexpr std::uint8_t ino_timer_oc_num[] = {
#if defined(AVR_ATmega328PB)
	(3 * 3 + 0),        /* 0 - port D */
	(4 * 3 + 0),
	(4 * 3 + 1), // (3 * 3 + 1) or (4 * 3 + 1)
#else
	0,
	0,
	0,
#endif
	// on the ATmega168, digital pin 3 has hardware pwm
#if defined(__AVR_ATmega8__)
	0,
#else
	(2 * 3 + 1),
#endif
	0,
	// on the ATmega168, digital pins 5 and 6 have hardware pwm
#if defined(__AVR_ATmega8__)
	0,
	0,
#else
	(0 * 3 + 1),
	(0 * 3 + 0),
#endif
	0,
	0,   /* 8 - port B */
	(1 * 3 + 0),
	(1 * 3 + 1),
#if defined(__AVR_ATmega8__)
	(2 * 3 + 0),
#else
	(2 * 3 + 0),
#endif
	0,
	0,
	0,
	0,   /* 14 - port C */
	0,
	0,
	0,
	0,
#if defined(__AVR_ATmega328PB__)
	0,   /* 20 - port E */
	0,
	0,
	0,
#endif
};

#endif

// These serial port names are intended to allow libraries and architecture-neutral
// sketches to automatically default to the correct port name for a particular type
// of use.  For example, a GPS module would normally connect to SERIAL_PORT_HARDWARE_OPEN,
// the first hardware serial port whose RX/TX pins are not dedicated to another use.
//
// SERIAL_PORT_MONITOR        Port which normally prints to the Arduino Serial Monitor
//
// SERIAL_PORT_USBVIRTUAL     Port which is USB virtual serial
//
// SERIAL_PORT_LINUXBRIDGE    Port which connects to a Linux system via Bridge library
//
// SERIAL_PORT_HARDWARE       Hardware serial port, physical RX & TX pins.
//
// SERIAL_PORT_HARDWARE_OPEN  Hardware serial ports which are open for use.  Their RX & TX
//                            pins are NOT connected to anything by default.
#define SERIAL_PORT_MONITOR   Serial
#define SERIAL_PORT_HARDWARE  Serial

#endif
