#define FH_DECLARE_AVR_GPIO_PIN(PORTNUM) \
static constexpr auto pin ## PORTNUM = details::avr_pin<decltype(avr::pin##PORTNUM), decltype(avr::port##PORTNUM), decltype(avr::ddr##PORTNUM)>{};

#define FH_DECLARE_AVR_GPIO_PORT(CODE)\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 0);\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 1);\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 2);\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 3);\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 4);\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 5);\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 6);\
FH_DECLARE_AVR_GPIO_PIN(CODE ## 7);\


#ifdef PORTA
FH_DECLARE_AVR_GPIO_PORT(A)
#endif
#ifdef PORTB
FH_DECLARE_AVR_GPIO_PORT(B)
#endif
#ifdef PORTC
FH_DECLARE_AVR_GPIO_PORT(C)
#endif
#ifdef PORTD
FH_DECLARE_AVR_GPIO_PORT(D)
#endif
#ifdef PORTE
FH_DECLARE_AVR_GPIO_PORT(E)
#endif
#ifdef PORTF
FH_DECLARE_AVR_GPIO_PORT(F)
#endif
#ifdef PORTG
FH_DECLARE_AVR_GPIO_PORT(G)
#endif
#ifdef PORTH
FH_DECLARE_AVR_GPIO_PORT(H)
#endif
#ifdef PORTJ
FH_DECLARE_AVR_GPIO_PORT(J)
#endif
#ifdef PORTK
FH_DECLARE_AVR_GPIO_PORT(K)
#endif
#ifdef PORTL
FH_DECLARE_AVR_GPIO_PORT(L)
#endif

#undef FH_DECLARE_AVR_GPIO_PORT
