// ********************* Generated by a tool *********************
/*
  ************************************************************************
  *	pins_fastduino.hpp
  *
  *	Arduino core files for MSP430
  * Copyright (c) 2014 Daniel Berenguer (panStamp)
  *
  ***********************************************************************
  Derived from:
  pins_fastduino.hpp - Pin definition functions for Arduino
  Part of Arduino - http://www.arduino.cc/

  Copyright (c) 2007 David A. Mellis

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General
  Public License along with this library; if not, write to the
  Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA  02111-1307  USA
*/

#ifndef FH_PINS_FASTDUINO_H_
#define FH_PINS_FASTDUINO_H_



// SPI CC1101 interface
#define CC1101_SPI_SS   10      // PB2 = SPI_SS
#define CC1101_GDO0	    2      // PD2 = INT0

// LD-BOARD definitions
#define HGM     20
#define LNA_EN  19
#define PA_EN   18

#define NUM_DIGITAL_PINS            20
#define NUM_ANALOG_INPUTS           6
#define analogInputToDigitalPin(p)  ((p < 6) ? (p) + 14 : -1)

#if defined(__AVR_ATmega8__)
#define digitalPinHasPWM(p)         ((p) == 9 || (p) == 10 || (p) == 11)
#else
#define digitalPinHasPWM(p)         ((p) == 3 || (p) == 5 || (p) == 6 || (p) == 9 || (p) == 10 || (p) == 11)
#endif

static constexpr std::uint8_t SS   = 10;
static constexpr std::uint8_t MOSI = 11;
static constexpr std::uint8_t MISO = 12;
static constexpr std::uint8_t SCK  = 13;

static constexpr std::uint8_t SDA = 18;
static constexpr std::uint8_t SCL = 19;
#define LED  4

static constexpr std::uint8_t A0 = 14;
static constexpr std::uint8_t A1 = 15;
static constexpr std::uint8_t A2 = 16;
static constexpr std::uint8_t A3 = 17;
static constexpr std::uint8_t A4 = 18;
static constexpr std::uint8_t A5 = 19;
static constexpr std::uint8_t A6 = 20;
static constexpr std::uint8_t A7 = 21;

// Preferred analog pin to measure battery voltage
#define BATT_VOLT_PIN   A0

// ADC resolution
#define ADC_RESOLUTION  1023

#define digitalPinToPCICR(p)    (((p) >= 0 && (p) <= 21) ? (&PCICR) : ((std::uint8_t *)0))
#define digitalPinToPCICRbit(p) (((p) <= 7) ? 2 : (((p) <= 13) ? 0 : 1))
#define digitalPinToPCMSK(p)    (((p) <= 7) ? (&PCMSK2) : (((p) <= 13) ? (&PCMSK0) : (((p) <= 21) ? (&PCMSK1) : ((std::uint8_t *)0))))
#define digitalPinToPCMSKbit(p) (((p) <= 7) ? (p) : (((p) <= 13) ? ((p) - 8) : ((p) - 14)))

#define digitalPinToInterrupt(p)  ((p) == 2 ? 0 : ((p) == 3 ? 1 : NOT_AN_INTERRUPT))

#if (2 + 2 == 4)

// On the Arduino board, digital pins are also used
// for the analog output (software PWM).  Analog input
// pins are a separate set.

//                               +-----------+
//                         GND  1|    ||||   |24  GND
//                   (D8)  PB0  2|           |23  GND
//             (PWM) (D9)  PB1  3|           |22  PD7 (D7)
//              (A0) (D14) PC0  4|           |21  PD6 (D6) (PWM)
//              (A1) (D15) PC1  5|           |20  PD5 (D5) (PWM)
//              (A2) (D16) PC2  6|           |19  PD4 (D4)
//                         GND  7|           |18  PD3 (D3) (PWM)
//              (A3) (D17) PC3  8|           |17  PD1 (UART_TX) (D1)
//    (I2C SDA) (A4) (D18) PC4  9|           |16  PD0 (UART_RX) (D0)
//    (I2C SCL) (A5) (D19) PC5 10|           |15  GND
//                    (A6) PC6 11|           |14  VCC
//                    (A7) PC7 12|           |13  RST
//                               +-----------+
//                               | | | | | | |
//                              A7 | | | | | RST
//                               VCC | | | SPI_MOSI
//                                 GND | SPI_MISO
//                                  SPI_SCK
//

// ATMEL ATMEGA1280 / ARDUINO
//
// 0-7 PE0-PE7   works
// 8-13 PB0-PB5  works
// 14-21 PA0-PA7 works 
// 22-29 PH0-PH7 works
// 30-35 PG5-PG0 works
// 36-43 PC7-PC0 works
// 44-51 PJ7-PJ0 works
// 52-59 PL7-PL0 works
// 60-67 PD7-PD0 works
// A0-A7 PF0-PF7
// A8-A15 PK0-PK7

// these arrays map port names (e.g. port B) to the
// appropriate addresses for various functions (e.g. reading
// and writing)






constexpr std::uint8_t ino_port_num[] = {
	4, /* 0 */
	4,
	4,
	4,
	4,
	4,
	4,
	4,
	2, /* 8 */
	2,
	2,
	2,
	2,
	2,
	3, /* 14 */
	3,
	3,
	3,
	3,
	3,
};

constexpr std::uint8_t ino_pin_num[] = {
	0, /* 0, port D */
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	0, /* 8, port B */
	1,
	2,
	3,
	4,
	5,
	0, /* 14, port C */
	1,
	2,
	3,
	4,
	5,
};

constexpr std::uint8_t ino_timer_oc_num[] = {
	0, /* 0 - port D */
	0,
	0,
	// on the ATmega168, digital pin 3 has hardware pwm
#if defined(__AVR_ATmega8__)
	0,
#else
	(2 * 3 + 1),
#endif
	0,
	// on the ATmega168, digital pins 5 and 6 have hardware pwm
#if defined(__AVR_ATmega8__)
	0,
	0,
#else
	(0 * 3 + 1),
	(0 * 3 + 0),
#endif
	0,
	0, /* 8 - port B */
	(1 * 3 + 0),
	(1 * 3 + 1),
#if defined(__AVR_ATmega8__)
	(2 * 3 + 0),
#else
	(2 * 3 + 0),
#endif
	0,
	0,
	0,
	0, /* 14 - port C */
	0,
	0,
	0,
	0,
};

#endif

// These serial port names are intended to allow libraries and architecture-neutral
// sketches to automatically default to the correct port name for a particular type
// of use.  For example, a GPS module would normally connect to SERIAL_PORT_HARDWARE_OPEN,
// the first hardware serial port whose RX/TX pins are not dedicated to another use.
//
// SERIAL_PORT_MONITOR        Port which normally prints to the Arduino Serial Monitor
//
// SERIAL_PORT_USBVIRTUAL     Port which is USB virtual serial
//
// SERIAL_PORT_LINUXBRIDGE    Port which connects to a Linux system via Bridge library
//
// SERIAL_PORT_HARDWARE       Hardware serial port, physical RX & TX pins.
//
// SERIAL_PORT_HARDWARE_OPEN  Hardware serial ports which are open for use.  Their RX & TX
//                            pins are NOT connected to anything by default.
#define SERIAL_PORT_MONITOR   Serial
#define SERIAL_PORT_HARDWARE  Serial

#endif
