// ********************* Generated by a tool *********************
/*
  NIBOburger library for ARDUINO
  License: BSD-License
  (c) 2013 by Nils Springob, nicai-systems
*/

#ifndef FH_PINS_FASTDUINO_H_
#define FH_PINS_FASTDUINO_H_




#define TOTAL_PINS              32
#define TOTAL_ANALOG_PINS       8
#define FIRST_ANALOG_PIN        24

#define WLED                    17

// How many ports are on this device
#define WIRING_PORTS 4

/*************************************************************
 * Prototypes
 *************************************************************/

void boardInit(void);


/*************************************************************
 * Pin locations - constexprants
 *************************************************************/

// SPI port
constexpr static std::uint8_t SS   = 20;
constexpr static std::uint8_t MOSI = 21;
constexpr static std::uint8_t MISO = 22;
constexpr static std::uint8_t SCK  = 23;

// TWI port
constexpr static std::uint8_t SCL  = 8;
constexpr static std::uint8_t SDA  = 9;

// Analog pins
constexpr static std::uint8_t A0 = 0;
constexpr static std::uint8_t A1 = 1;
constexpr static std::uint8_t A2 = 2;
constexpr static std::uint8_t A3 = 3;
constexpr static std::uint8_t A4 = 4;
constexpr static std::uint8_t A5 = 5;
constexpr static std::uint8_t A6 = 6;
constexpr static std::uint8_t A7 = 7;

// External Interrupts
constexpr static std::uint8_t EI0 = 2;
constexpr static std::uint8_t EI1 = 3;
constexpr static std::uint8_t EI2 = 18;

// Hardware Serial port pins
constexpr static std::uint8_t RX0 = 0;
constexpr static std::uint8_t TX0 = 1;


// NIBO burger IO definitions

enum {
  // PORT D
  IO_RXD     =  0,
  IO_TXD     =  1,
  IO_ODO_L   =  2,
  IO_ODO_R   =  3,
  IO_PWM_L   =  4,
  IO_PWM_R   =  5,
  IO_DIR_L   =  6,
  IO_DIR_R   =  7,
 
  // PORT C
  IO_SCL     =  8,
  IO_SDA     =  9,
  IO_EN_FLL  = 10,
  IO_EN_FRR  = 11,
  IO_EN_FL   = 12,
  IO_EN_FR   = 13,
  IO_EN_BL   = 14,
  IO_EN_BR   = 15,
  
  // PORT B
  IO_EN_BC   = 16,
  IO_LED1    = 17,
  IO_LED2    = 18,
  IO_LED3    = 19,
  IO_LED4    = 20,
  IO_MOSI    = 21,
  IO_MISO    = 22,
  IO_SCK     = 23,
  
  // PORT A
  IO_AN_FL   = 24,
  IO_AN_FR   = 25,
  IO_AN_BL   = 26,
  IO_AN_BR   = 27,
  IO_AN_KEY  = 28,
  IO_AN_FLL  = 29,
  IO_AN_BC   = 30,
  IO_AN_FRR  = 31
};


/*************************************************************
 * Pin to register mapping macros
 *************************************************************/

#define digitalPinToPortReg(PIN) \
        ( ((PIN) >= 0  && (PIN) <= 7)  ? &PORTD : \
        ( ((PIN) >= 8  && (PIN) <= 15) ? &PORTC : \
        ( ((PIN) >= 16 && (PIN) <= 23) ? &PORTB : \
        ( ((PIN) >= 24 && (PIN) <= 31) ? &PORTA : NOT_A_REG))))

#define digitalPinToBit(P)       ((P) & 7)



/*************************************************************
 * Timer prescale factors
 *************************************************************/

#define TIMER0PRESCALEFACTOR 64


#if (2 + 2 == 4)







constexpr std::uint8_t ino_port_num[] = {
	// PORTLIST		
	// -------------------------------------------		
	4	, // 4
	4	, // 4
	4	, // 4
	4	, // 4
	4	, // 4
	4	, // 4
	4	, // 4
	4	, // 4
	3	, // 3
	3	, // 3
	3	, // 3
	3	, // 3
	3	, // 3
	3	, // 3
	3	, // 3
	3	, // 3
	2	, // 2
	2	, // 2
	2	, // 2
	2	, // 2
	2	, // 2
	2	, // 2
	2	, // 2
	2	, // 2
	1	, // 1
	1	, // 1
	1	, // 1
	1	, // 1
	1	, // 1
	1	, // 1
	1	, // 1
	1	, // 1
};

constexpr std::uint8_t ino_pin_num[] = {
	// PIN IN PORT		
	// -------------------------------------------		
	 0 	, // PD 0
	 1 	, // PD 1
	 2 	, // PD 2
	 3 	, // PD 3
	 4 	, // PD 4
	 5 	, // PA 5
	 6 	, // PA 6
	 7 	, // PA 7
	 0 	, // PA 0
	 1 	, // PA 1
	 2 	, // PA 2
	 3 	, // PA 3
	 4 	, // PA 4
	 5 	, // PA 5
	 6 	, // PA 6
	 7 	, // PA 7
	 0 	, // PA 0
	 1 	, // PA 1
	 2 	, // PA 2
	 3 	, // PA 3
	 4 	, // PA 4
	 5 	, // PA 5
	 6 	, // PA 6
	 7 	, // PA 7
	 0 	, // PA 0
	 1 	, // PA 1
	 2 	, // PA 2
	 3 	, // PA 3
	 4 	, // PA 4
	 5 	, // PA 5
	 6 	, // PA 6
	 7 	, // PA 7
};

constexpr std::uint8_t ino_timer_oc_num[] = {
	// TIMERS		
	// -------------------------------------------		
	0	, // PD 0
	0	, // PD 1
	0	, // PD 2
	0	, // PD 3
	(1 * 3 + 1)		, // PD 4
	(1 * 3 + 0)		, // PA 5
	0	, // PA 6
	0	, // PH 4
	0	, // PH 5
	0	, // PH 6
	0	, // PB 4
	0	, // PB 5
	0	, // PB 6
	0	, // PB 7
	0	, // PJ 1
	0	, // PJ 0
	0	, // PH 1
	0	, // PH 0
	0	, // PD 3
	0	, // PD 2
	0	, // PD 1
	0	, // PD 0
	0	, // PA 0
	0	, // PA 1
	0	, // PA 2
	0	, // PA 3
	0	, // PA 4
	0	, // PA 5
	0	, // PA 6
	0	, // PA 7 ** 29 ** D29	
	0	, // PC 7 ** 30 ** D30	
	0	, // PC 6 ** 31 ** D31	
	0	, // PC 5 ** 32 ** D32	
	0	, // PC 4 ** 33 ** D33	
	0	, // PC 3 ** 34 ** D34	
	0	, // PC 2 ** 35 ** D35	
	0	, // PC 1 ** 36 ** D36	
	0	, // PC 0 ** 37 ** D37	
	0	, // PD 7 ** 38 ** D38	
	0	, // PG 2 ** 39 ** D39	
	0	, // PG 1 ** 40 ** D40	
	0	, // PG 0 ** 41 ** D41	
	0	, // PL 7 ** 42 ** D42	
	0	, // PL 6 ** 43 ** D43	
	0	, // PL 5 ** 44 ** D44	
	0	, // PL 4 ** 45 ** D45	
	0	, // PL 3 ** 46 ** D46	
	0	, // PL 2 ** 47 ** D47	
	0	, // PL 1 ** 48 ** D48	
	0	, // PL 0 ** 49 ** D49	
	0	, // PB 3 ** 50 ** SPI_MISO	
	0	, // PB 2 ** 51 ** SPI_MOSI	
	0	, // PB 1 ** 52 ** SPI_SCK	
	0	, // PB 0 ** 53 ** SPI_SS	
	0	, // PF 0 ** 54 ** A0	
	0	, // PF 1 ** 55 ** A1	
	0	, // PF 2 ** 56 ** A2	
	0	, // PF 3 ** 57 ** A3	
	0	, // PF 4 ** 58 ** A4	
	0	, // PF 5 ** 59 ** A5	
	0	, // PF 6 ** 60 ** A6	
	0	, // PF 7 ** 61 ** A7	
	0	, // PK 0 ** 62 ** A8	
	0	, // PK 1 ** 63 ** A9	
	0	, // PK 2 ** 64 ** A10	
	0	, // PK 3 ** 65 ** A11	
	0	, // PK 4 ** 66 ** A12	
	0	, // PK 5 ** 67 ** A13	
	0	, // PK 6 ** 68 ** A14	
	0	, // PK 7 ** 69 ** A15	
};

#endif


#endif
// BOARDDEFS_H
