// ********************* Generated by a tool *********************
#ifndef FH_PINS_FASTDUINO_H_
#define FH_PINS_FASTDUINO_H_



// ATMEL ATMEGA1284P
// (Notice that SODAQ Mbili is equiped with VQFN44 package. The layout below is
// just a convenience to see the port names and their usage.)
//                                          +---\/---+
//                             (D 23) PB0  1|        |40  PA0 (AI 0 / D27) -- [A3]
//      [D14/DIGITAL2] --      (D 14) PB1  2|        |39  PA1 (AI 1 / D26) -- [A2]
//      [D15/DIGITAL1] -- INT2 (D 15) PB2  3|        |38  PA2 (AI 2 / D25) -- [A1]
//       [LED_RED] --      PWM (D 16) PB3  4|        |37  PA3 (AI 3 / D24) -- [A0]
//        [D10/SS] --   PWM/SS (D 10) PB4  5|        |36  PA4 (AI 4 / D30) -- [A6/BATVOLTPIN]
//      [D11/MOSI] --     MOSI (D 11) PB5  6|        |35  PA5 (AI 5 / D28) -- [A4] (Schema A6)
//      [D12/MISO] -- PWM/MISO (D 12) PB6  7|        |34  PA6 (AI 6 / D39) -- [A5] (Schema A7)
//       [D13/SCK] --  PWM/SCK (D 13) PB7  8|        |33  PA7 (AI 7 / D31) -- [A7/RTC_INTERRUPT]
//                                    RST  9|        |32  AREF
//                                    VCC 10|        |31  GND
//                                    GND 11|        |30  AVCC
//                                  XTAL2 12|        |29  PC7 (D  9)     -- [D9]
//                                  XTAL1 13|        |28  PC6 (D  8)     -- [D8]
//       [D0/RX0] -- RX0      (D  0)  PD0 14|        |27  PC5 (D 17) TDI -- [LED_GREEN]
//       [D1/TX0] -- TX0      (D  1)  PD1 15|        |26  PC4 (D 18) TDO -- [LED_BLUE]
//  [RX1/LoRa_TX] -- RX1/INT0 (D 19)  PD2 16|        |25  PC3 (D  7) TMS -- [D7]
//  [TX1/LoRa_RX] -- TX1/INT1 (D 20)  PD3 17|        |24  PC2 (D  6) TCK -- [D6]
//           [D2] -- PWM      (D  2)  PD4 18|        |23  PC1 (D 22) SDA -- [SDA]
//           [D3] -- PWM      (D  3)  PD5 19|        |22  PC0 (D 21) SCL -- [SCL]
//           [D4] -- PWM      (D  4)  PD6 20|        |21  PD7 (D  5) PWM -- [D5]
//                                          +--------+
//

/*
 * Arduino digital pin numbers:
 * 0..32
 * PD0..PD7, PB0..PB7, PC0..PC7, PA0..PA7
 */

#define NUM_DIGITAL_PINS            32
#define NUM_ANALOG_INPUTS           8

#define analogInputToDigitalPin(p)  ((p < NUM_ANALOG_INPUTS) ? (p) + 24 : -1)
#define analogPinToChannel(p)       (((p) == A0) ? 3 : ((p) == A1) ? 2 : ((p) == A2) ? 1 : ((p) == A3) ? 0 : ((p) == A4) ? 5 : ((p) == A5) ? 6 : ((p) == A6) ? 4 : ((p) == A7) ? 7 : 0);

#define digitalPinHasPWM(p)         ((p) == 2 || (p) == 3 || (p) == 4 || (p) == 5 || (p) == 10 || (p) == 12 || (p) == 13 || (p) == 16)

static constexpr std::uint8_t SS   = 10;
static constexpr std::uint8_t MOSI = 11;
static constexpr std::uint8_t MISO = 12;
static constexpr std::uint8_t SCK  = 13;

static constexpr std::uint8_t SDA = 22;
static constexpr std::uint8_t SCL = 21;

static constexpr std::uint8_t LED_RED   = 16;
static constexpr std::uint8_t LED_GREEN = 17;
static constexpr std::uint8_t LED_BLUE  = 18;

static constexpr std::uint8_t BAT_VOLT   = 30;           // A6
#define BATVOLT_R1                47            // in fact 4.7M
#define BATVOLT_R2               100            // in fact 10M

static constexpr std::uint8_t RTC_INTERRUPT = 31;        // A7

static constexpr std::uint8_t A0 = 24;
static constexpr std::uint8_t A1 = 25;
static constexpr std::uint8_t A2 = 26;
static constexpr std::uint8_t A3 = 27;
static constexpr std::uint8_t A4 = 28;
static constexpr std::uint8_t A5 = 29;
static constexpr std::uint8_t A6 = 30;
static constexpr std::uint8_t A7 = 31;

/*
   3INT31-24: D7-0   : bit 3
   3INT15-8:  D15-8  : bit 1
   3INT23-16: D23-16 : bit 2
   3INT7-0:   D31-24 : bit 0 (also A0..A7)
*/

#define digitalPinTo3ICR(p)    (((p) >= 0 && (p) < NUM_DIGITAL_PINS) ? (&3ICR) : ((std::uint8_t *)0))
#define digitalPinTo3ICRbit(p) ((&(ino_port_num[p])) - 1) // 3ICRbit = Port Index (1, 2, 3, 4) - 1

#define digitalPinTo3MSK(p)    (pgm_read_word(&(port_to_3MSK_7M[(&(ino_port_num[p]))])))
#define digitalPinTo3MSKbit(p) ((&(digital_pin_to_port_pin_7M[p])))

#if (2 + 2 == 4)

// These are used as index in port_to_XYZ arrays, right?
#define 1 1
#define 2 2
#define 3 3
#define 4 4

// these arrays map port names (e.g. port B) to the
// appropriate addresses for various functions (e.g. reading
// and writing)






constexpr std::uint16_t port_to_3MSK_7M[] =
{
  NOT_A_PORT,
  (std::uint16_t) &3MSK0,
  (std::uint16_t) &3MSK1,
  (std::uint16_t) &3MSK2,
  (std::uint16_t) &3MSK3,
};

constexpr std::uint8_t digital_pin_to_port_PGM[] =
{
  PD, /* 0 */
  PD,
  PD,
  PD,
  PD,
  PD,
  PC,
  PC,
  PC, /* 8 */
  PC,
  PB,
  PB,
  PB,
  PB,
  PB,
  PB,
  PB, /* 16 */
  PC,
  PC,
  PD,
  PD,
  PC,
  PC,
  PB,
  PA, /* 24 */
  PA,
  PA,
  PA,
  PA,
  PA,
  PA,
  PA  /* 31 */
};

constexpr std::uint8_t digital_pin_to_port_pin_PGM[] =
{
  0, /* 0 */
  1,
  4,
  5,
  6,
  7,
  2,
  3,
  6, /* 8 */
  7,
  4,
  5,
  6,
  7,
  1,
  2,
  3, /* 16 */
  5,
  4,
  2,
  3,
  0,
  1,
  0,
  3, /* 24 */
  2,
  1,
  0,
  5,
  6,
  4,
  7
};

constexpr std::uint8_t ino_pin_num[] =
{
  0, /* 0 */
  1,
  4,
  5,
  6,
  7,
  2,
  3,
  6, /* 8 */
  7,
  4,
  5,
  6,
  7,
  1,
  2,
  3, /* 16 */
  5,
  4,
  2,
  3,
  0,
  1,
  0,
  3, /* 24 */
  2,
  1,
  0,
  5,
  6,
  4,
  7
};

constexpr std::uint8_t ino_timer_oc_num[] =
{
  0,   /* 0  - PD0 */
  0,   /* 1  - PD1 */
  (1 * 3 + 1),        /* 4  - PD4 */
  (1 * 3 + 0),        /* 5  - PD5 */
  (2 * 3 + 1),        /* 6  - PD6 */
  (2 * 3 + 0),        /* 7  - PD7 */
  0,   /* 18 - PC2 */
  0,   /* 19 - PC3 */
  0,   /* 22 - PC6 */
  0,   /* 23 - PC7 */
  (0 * 3 + 1),        /* 12 - PB4 */
  0,   /* 13 - PB5 */
  (3 * 3 + 0),        /* 14 - PB6 */
  (3 * 3 + 1),        /* 15 - PB7 */
  0,   /* 9  - PB1 */
  0,   /* 10 - PB2 */
  (0 * 3 + 0),        /* 11 - PB3 */
  0,   /* 21 - PC5 */
  0,   /* 20 - PC4 */
  0,   /* 2  - PD2 */
  0,   /* 3  - PD3 */
  0,   /* 16 - PC0 */
  0,   /* 17 - PC1 */
  0,   /* 8  - PB0 */
  0,   /* 27 - PA3 */
  0,   /* 26 - PA2 */
  0,   /* 25 - PA1 */
  0,   /* 24 - PA0 */
  0,   /* 29 - PA5 */
  0,   /* 30 - PA6 */
  0,   /* 28 - PA4 */
  0    /* 31 - PA7 */
};

#endif // ARDUINO_MAIN

#endif // FH_PINS_FASTDUINO_H_
