// ********************* Generated by a tool *********************
/*
  NIBO2 library for ARDUINO
  License: BSD-License
  (c) 2013 by Nils Springob, nicai-systems
*/

#ifndef FH_PINS_FASTDUINO_H_
#define FH_PINS_FASTDUINO_H_



#define TOTAL_PINS              53
#define TOTAL_ANALOG_PINS       8
#define FIRST_ANALOG_PIN        40

#define WLED                    16

// How many ports are on this device
#define WIRING_PORTS 7

/*************************************************************
 * Prototypes
 *************************************************************/

void boardInit(void);


/*************************************************************
 * Pin locations - constexprants
 *************************************************************/

// SPI port
constexpr static uint8_t SS   = 8;
constexpr static uint8_t MOSI = 10;
constexpr static uint8_t MISO = 11;
constexpr static uint8_t SCK  = 9;

// TWI port
constexpr static uint8_t SCL  = 24;
constexpr static uint8_t SDA  = 25;

// Analog pins
constexpr static uint8_t A0 = 0;
constexpr static uint8_t A1 = 1;
constexpr static uint8_t A2 = 2;
constexpr static uint8_t A3 = 3;
constexpr static uint8_t A4 = 4;
constexpr static uint8_t A5 = 5;
constexpr static uint8_t A6 = 6;
constexpr static uint8_t A7 = 7;

// External Interrupts
constexpr static uint8_t EI0 = 24;
constexpr static uint8_t EI1 = 25;
constexpr static uint8_t EI2 = 26;
constexpr static uint8_t EI3 = 27;

// Hardware Serial port pins
constexpr static uint8_t RX0 = 32;
constexpr static uint8_t TX0 = 33;
constexpr static uint8_t RX1 = 26;
constexpr static uint8_t TX1 = 27;


// NIBO 2 IO definitions

enum {
  /* PORT A */
  IO_LCD_D0     =  0,
  IO_LCD_D1     =  1,
  IO_LCD_D2     =  2,
  IO_LCD_D3     =  3,
  IO_LCD_D4     =  4,
  IO_LCD_D5     =  5,
  IO_LCD_D6     =  6,
  IO_LCD_D7     =  7,

  /* PORT B */
  IO_SS         =  8,
  IO_SCK        =  9,
  IO_MOSI       = 10,
  IO_MISO       = 11,
  IO_AUDIO      = 12,
  IO_LED_W_PWM  = 13,
  IO_LCD_PWM    = 14,
  IO_LED_RG_PWM = 15,

  /* PORT C */
  IO_LED_G0     = 16,
  IO_LED_G1     = 17,
  IO_LED_G2     = 18,
  IO_LED_G3     = 19,
  IO_LED_G4     = 20,
  IO_LED_G5     = 21,
  IO_LED_G6     = 22,
  IO_LED_G7     = 23,

  /* PORT D */
  IO_I2C_SCL    = 24,
  IO_I2C_SDA    = 25,
  IO_EXT_D      = 26,
  IO_EXT_C      = 27,
  IO_INPUT1     = 28,
  IO_EXT_B      = 29,
  IO_EXT_A      = 30,
  IO_RESET_IC2  = 31,
  
  /* PORT E */
  IO_LED_R0     = 32,
  IO_LED_R1     = 33,
  IO_LED_R2     = 34,
  IO_LED_R3     = 35,
  IO_LED_R4     = 36,
  IO_LED_R5     = 37,
  IO_LED_R6     = 38,
  IO_LED_R7     = 39,
  
  /* PORT F */
  IO_FLOOR0     = 40,
  IO_FLOOR1     = 41,
  IO_FLOOR2     = 42,
  IO_FLOOR3     = 43,
  IO_INPUT3     = 44,
  IO_INPUT2     = 45,
  IO_FLOOR_EN   = 46,
  IO_SUPPLY     = 47,
  
  /* PORT G */ 
  IO_LCD_CS1    = 48,
  IO_LCD_CS2    = 49,
  IO_LCD_EN     = 50,
  IO_LCD_RS     = 51,
  IO_LCD_RW     = 52
};

#define IO_RXD0 IO_LED_R0
#define IO_TXD0 IO_LED_R1
#define IO_RXD1 IO_EXT_D
#define IO_TXD1 IO_EXT_C



/*************************************************************
 * Pin to register mapping macros
 *************************************************************/

#define digitalPinToPortReg(PIN) \
        ( ((PIN) >=  0 && (PIN) <=  7) ? &PORTA : \
        ( ((PIN) >=  8 && (PIN) <= 15) ? &PORTB : \
        ( ((PIN) >= 16 && (PIN) <= 23) ? &PORTC : \
        ( ((PIN) >= 24 && (PIN) <= 31) ? &PORTD : \
        ( ((PIN) >= 32 && (PIN) <= 39) ? &PORTE : \
        ( ((PIN) >= 40 && (PIN) <= 47) ? &PORTF : \
        ( ((PIN) >= 48 && (PIN) <= 52) ? &PORTG : \
                                         NOT_A_REG))))

#define digitalPinToBit(P)       ((P) & 7)



/*************************************************************
 * Timer prescale factors
 *************************************************************/

#define TIMER0PRESCALEFACTOR 64


#if (2 + 2 == 4)







constexpr std::uint8_t ino_port_num[] = {
	// PORTLIST		
	// -------------------------------------------		
	1	, // 1 0
	1	, // 1 1
	1	, // 1 2
	1	, // 1 3
	1	, // 1 4
	1	, // 1 5
	1	, // 1 6
	1	, // 1 7
	2	, // 2 0
	2	, // 2 1
	2	, // 2 2
	2	, // 2 3
	2	, // 2 4
	2	, // 2 5
	2	, // 2 6
	2	, // 2 7
	3	, // 3 0
	3	, // 3 1
	3	, // 3 2
	3	, // 3 3
	3	, // 3 4
	3	, // 3 5
	3	, // 3 6
	3	, // 3 7
	4	, // 4 0
	4	, // 4 1
	4	, // 4 2
	4	, // 4 3
	4	, // 4 4
	4	, // 4 5
	4	, // 4 6
	4	, // 4 7
	5	, // 5 0
	5	, // 5 1
	5	, // 5 2
	5	, // 5 3
	5	, // 5 4
	5	, // 5 5
	5	, // 5 6
	5	, // 5 7
	6	, // 6 0
	6	, // 6 1
	6	, // 6 2
	6	, // 6 3
	6	, // 6 4
	6	, // 6 5
	6	, // 6 6
	6	, // 6 7
	7	, // 7 0
	7	, // 7 1
	7	, // 7 2
	7	, // 7 3
	7	, // 7 4
};

constexpr std::uint8_t ino_pin_num[] = {
	// PIN IN PORT		
	// -------------------------------------------		
	 0 	, // PA 0
	 1 	, // PA 1
	 2 	, // PA 2
	 3 	, // PA 3
	 4 	, // PA 4
	 5 	, // PA 5
	 6 	, // PA 6
	 7 	, // PA 7
	 0 	, // PB 0
	 1 	, // PB 1
	 2 	, // PB 2
	 3 	, // PB 3
	 4 	, // PB 4
	 5 	, // PB 5
	 6 	, // PB 6
	 7 	, // PB 7
	 0 	, // PC 0
	 1 	, // PC 1
	 2 	, // PC 2
	 3 	, // PC 3
	 4 	, // PC 4
	 5 	, // PC 5
	 6 	, // PC 6
	 7 	, // PC 7
	 0 	, // PD 0
	 1 	, // PD 1
	 2 	, // PD 2
	 3 	, // PD 3
	 4 	, // PD 4
	 5 	, // PD 5
	 6 	, // PD 6
	 7 	, // PD 7
	 0 	, // PE 0
	 1 	, // PE 1
	 2 	, // PE 2
	 3 	, // PE 3
	 4 	, // PE 4
	 5 	, // PE 5
	 6 	, // PE 6
	 7 	, // PE 7
	 0 	, // PF 0
	 1 	, // PF 1
	 2 	, // PF 2
	 3 	, // PF 3
	 4 	, // PF 4
	 5 	, // PF 5
	 6 	, // PF 6
	 7 	, // PF 7
	 0 	, // PG 0
	 1 	, // PG 1
	 2 	, // PG 2
	 3 	, // PG 3
	 4 	, // PG 4
};

constexpr std::uint8_t ino_timer_oc_num[] = {
	/* PORT A */
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	
	/* PORT B */
	255,
	255,
	255,
	255,
	(0'0),
	(1'0),
	(1'1),
	(1'2),
	
	/* PORT C */
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	
	/* PORT D */
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	
	/* PORT E */
	255,
	255,
	255,
	(3'0),
	(3'1),
	(3'2),
	255,
	255,
	
	/* PORT F */
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	255,
	
	/* PORT G */
	255,
	255,
	255,
	255,
	255
};

#endif


#endif
// BOARDDEFS_H
